# Generated by Django 3.0.4 on 2020-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.TextField(default='Assistant Professor')),
                ('education', models.TextField()),
                ('department', models.TextField()),
                ('description', models.TextField(default='No Description yet')),
                ('email', models.EmailField(default='mail@example.com', max_length=254)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('department', models.TextField()),
                ('instructor', models.ManyToManyField(to='reviews.Professor')),
            ],
        ),
    ]
