# Generated by Django 3.0.4 on 2020-03-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_prof_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
