# Generated by Django 3.0.4 on 2020-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20200328_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='No Description yet'),
        ),
    ]
