# Generated by Django 3.0.4 on 2020-03-30 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_review',
            name='Reports',
        ),
        migrations.RemoveField(
            model_name='prof_review',
            name='Reports',
        ),
        migrations.AddField(
            model_name='course_review',
            name='creports',
            field=models.ManyToManyField(blank=True, related_name='creports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prof_review',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course_review',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='prof_review',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
